Message: mime

Part 1
body-line-count => int(27)
charset => string(8) "us-ascii"
content-base => string(1) "/"
content-boundary => string(41) "----=_NextPart_000_0007_01C2566B.DA7C64F0"
content-type => string(15) "multipart/mixed"
ending-pos => int(1441)
line-count => int(47)
starting-pos => int(0)
starting-pos-body => int(836)
transfer-encoding => string(4) "8bit"

    Part 1.1
    body-line-count => int(1)
    charset => string(8) "us-ascii"
    content-base => string(1) "/"
    content-charset => string(8) "us-ascii"
    content-type => string(10) "text/plain"
    ending-pos => int(1053)
    line-count => int(5)
    starting-pos => int(926)
    starting-pos-body => int(1005)
    transfer-encoding => string(4) "7bit"

    Part 1.2
    body-line-count => int(7)
    charset => string(8) "us-ascii"
    content-base => string(1) "/"
    content-disposition => string(10) "attachment"
    content-name => string(6) "README"
    content-type => string(24) "application/octet-stream"
    disposition-filename => string(6) "README"
    ending-pos => int(1392)
    line-count => int(13)
    starting-pos => int(1098)
    starting-pos-body => int(1250)
    transfer-encoding => string(16) "quoted-printable"
